### ISSUE TITLE
Empty Slack username for users without display name

### ISSUE THREAD

**Issue by gdaniel** [jarvis-bot-platform/jarvis#214]
The `SlackIntentProvider` sets `slack.username` value with the the user's `display name`, which may be empty for users who didn't explicitly set a display name through the Slack interface.

We should look for another identifier (e.g. the full username) if the display name is empty. 

This issue has been reported by @nerlichman during the Jarvis tutorial (10/04)
Related to #36

**Comment by nerlichman** [comment]
Maybe the identifier “real_name” that based on Slack API documentation should retrieve the full name of the user.
